# Generated by Django 5.1.6 on 2025-03-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='liga',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='lugar',
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_local',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_visitante',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
