# Generated by Django 5.1.6 on 2025-03-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidos_jugados', models.PositiveIntegerField(default=0)),
                ('goles', models.PositiveIntegerField(default=0)),
                ('asistencias', models.PositiveIntegerField(default=0)),
                ('tarjetas_amarillas', models.PositiveIntegerField(default=0)),
                ('tarjetas_rojas', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
