# Generated by Django 5.1.6 on 2025-03-05 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0002_initial'),
        ('partidos', '0002_remove_partido_liga_remove_partido_lugar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadisticajugador',
            name='partidos_jugados',
        ),
        migrations.AddField(
            model_name='estadisticajugador',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partidos.partido'),
        ),
        migrations.AlterField(
            model_name='estadisticajugador',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to=settings.AUTH_USER_MODEL),
        ),
    ]
