# Generated by Django 5.1.6 on 2025-03-04 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
        ('ligas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='liga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ligas.liga'),
        ),
    ]
